/**
 * PlanReview — structured plan display + edit + approval gate.
 *
 * The user reviews the plan generated by `POST /agent/plans` before any
 * execution. Editable fields (universe symbols, dates, strategy params,
 * cost, factors) use inline antd inputs. On every edit the plan is
 * re-validated against the shared Zod schema; the "Approve & Run" button
 * is disabled until the plan passes validation.
 *
 * Plan hash: the hash returned by the planner is displayed. If the user
 * edits the plan, the hash will no longer match — we flag this with a
 * warning and the backend will reject the mismatch. The user can either
 * regenerate (revert to planner output) or confirm the edited plan (which
 * will fail on the backend, forcing a regenerate — a safety design choice).
 */
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Alert,
  Button,
  Card,
  DatePicker,
  Input,
  InputNumber,
  Select,
  Space,
  Tag,
  Typography,
} from 'antd';
import { CheckCircleOutlined, EditOutlined, PlayCircleOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';

import type { ResearchPlanT } from '@finresearch/shared';
import { researchPlanSchema } from '@finresearch/shared';

const { Text, Paragraph } = Typography;

interface PlanReviewProps {
  plan: ResearchPlanT;
  planHash: string | null;
  clarificationNeeded: string | null;
  validationErrors: string[];
  approving: boolean;
  onApprove: (plan: ResearchPlanT, planHash: string) => void;
  onRegenerate: () => void;
}

type EditableFields = 'universe' | 'benchmark' | 'dates' | 'cost' | 'factors';

function PlanReview({
  plan,
  planHash,
  clarificationNeeded,
  validationErrors,
  approving,
  onApprove,
  onRegenerate,
}: PlanReviewProps) {
  const { t } = useTranslation('agent');
  const [editing, setEditing] = useState<Set<EditableFields>>(new Set());
  const [draft, setDraft] = useState<ResearchPlanT>(plan);

  const isEditing = (field: EditableFields) => editing.has(field);

  const toggleEdit = (field: EditableFields) => {
    const next = new Set(editing);
    if (next.has(field)) {
      next.delete(field);
    } else {
      next.add(field);
    }
    setEditing(next);
  };

  // Re-validate the draft plan against the shared Zod schema on every change.
  const validationResult = useMemo(() => {
    return researchPlanSchema.safeParse(draft);
  }, [draft]);

  const hasEdits = JSON.stringify(draft) !== JSON.stringify(plan);
  const canApprove = validationResult.success && !hasEdits;

  const handleApprove = () => {
    if (!planHash || !validationResult.success) return;
    onApprove(validationResult.data, planHash);
  };

  const unresolvedAssets = draft.universe.filter((a) => !a.asset_id);
  const hasUnresolved = unresolvedAssets.length > 0;

  return (
    <Card
      title={
        <Space>
          <Text strong>{t('plan.title')}</Text>
          {plan.resolution === 'validated' ? (
            <Tag color="green">{t('plan.resolution')}: validated</Tag>
          ) : (
            <Tag color="orange">{t('plan.resolution')}: draft</Tag>
          )}
        </Space>
      }
      extra={
        <Button size="small" icon={<EditOutlined />} onClick={onRegenerate}>
          {t('plan.regenerate')}
        </Button>
      }
      className="agent-plan-review"
    >
      <Paragraph type="secondary">{t('plan.description')}</Paragraph>

      {clarificationNeeded && (
        <Alert
          type="info"
          showIcon
          message={t('plan.clarification')}
          description={clarificationNeeded}
          className="agent-alert"
        />
      )}

      {validationErrors.length > 0 && (
        <Alert
          type="warning"
          showIcon
          message={t('plan.validationErrors')}
          description={
            <ul className="agent-validation-list">
              {validationErrors.map((e, i) => (
                <li key={i}>{e}</li>
              ))}
            </ul>
          }
          className="agent-alert"
        />
      )}

      {hasUnresolved && (
        <Alert type="info" showIcon message={t('plan.unresolved')} className="agent-alert" />
      )}

      {hasEdits && (
        <Alert type="warning" showIcon message={t('plan.hashMismatch')} className="agent-alert" />
      )}

      <div className="agent-plan-fields">
        {/* Research Question */}
        <div className="agent-plan-field">
          <Text type="secondary" className="agent-plan-field-label">
            {t('plan.researchQuestion')}
          </Text>
          <Paragraph>{draft.research_question}</Paragraph>
        </div>

        {/* Universe */}
        <div className="agent-plan-field">
          <div className="agent-plan-field-header">
            <Text type="secondary" className="agent-plan-field-label">
              {t('plan.universe')}
            </Text>
            <Button type="link" size="small" onClick={() => toggleEdit('universe')}>
              {isEditing('universe') ? t('plan.done') : t('plan.edit')}
            </Button>
          </div>
          {isEditing('universe') ? (
            <Select
              mode="tags"
              value={draft.universe.map((a) => a.symbol)}
              onChange={(symbols) => {
                setDraft({
                  ...draft,
                  universe: symbols.map((s) => {
                    const existing = draft.universe.find((a) => a.symbol === s);
                    return existing ?? { symbol: s };
                  }),
                });
              }}
              style={{ width: '100%' }}
              tokenSeparators={[',', ' ']}
            />
          ) : (
            <Space wrap>
              {draft.universe.map((a) => (
                <Tag key={a.symbol} color={a.asset_id ? 'blue' : 'orange'}>
                  {a.symbol}
                </Tag>
              ))}
            </Space>
          )}
        </div>

        {/* Benchmark */}
        <div className="agent-plan-field">
          <div className="agent-plan-field-header">
            <Text type="secondary" className="agent-plan-field-label">
              {t('plan.benchmark')}
            </Text>
            <Button type="link" size="small" onClick={() => toggleEdit('benchmark')}>
              {isEditing('benchmark') ? t('plan.done') : t('plan.edit')}
            </Button>
          </div>
          {isEditing('benchmark') ? (
            <Input
              value={draft.benchmark.symbol}
              onChange={(e) =>
                setDraft({ ...draft, benchmark: { ...draft.benchmark, symbol: e.target.value } })
              }
              style={{ width: 200 }}
            />
          ) : (
            <Tag color={draft.benchmark.asset_id ? 'blue' : 'orange'}>
              {draft.benchmark.symbol}
            </Tag>
          )}
        </div>

        {/* Window */}
        <div className="agent-plan-field">
          <div className="agent-plan-field-header">
            <Text type="secondary" className="agent-plan-field-label">
              {t('plan.window')}
            </Text>
            <Button type="link" size="small" onClick={() => toggleEdit('dates')}>
              {isEditing('dates') ? t('plan.done') : t('plan.edit')}
            </Button>
          </div>
          {isEditing('dates') ? (
            <DatePicker.RangePicker
              value={[dayjs(draft.start_date), dayjs(draft.end_date)]}
              onChange={(_, dateStrings) => {
                if (dateStrings[0] && dateStrings[1]) {
                  setDraft({
                    ...draft,
                    start_date: `${dateStrings[0]}T00:00:00Z`,
                    end_date: `${dateStrings[1]}T00:00:00Z`,
                  });
                }
              }}
            />
          ) : (
            <Text>
              {dayjs(draft.start_date).format('YYYY-MM-DD')} →{' '}
              {dayjs(draft.end_date).format('YYYY-MM-DD')}
            </Text>
          )}
        </div>

        {/* Strategy */}
        <div className="agent-plan-field">
          <Text type="secondary" className="agent-plan-field-label">
            {t('plan.strategy')}
          </Text>
          <div>
            <Tag>{draft.strategy.name}</Tag>
            <Tag>{draft.strategy.rebalance}</Tag>
            {Object.entries(draft.strategy.params).map(([k, v]) => (
              <Tag key={k}>
                {k}: {String(v)}
              </Tag>
            ))}
          </div>
        </div>

        {/* Factors */}
        <div className="agent-plan-field">
          <Text type="secondary" className="agent-plan-field-label">
            {t('plan.factors')}
          </Text>
          <Space wrap>
            {draft.factors.length === 0 ? (
              <Text type="secondary">—</Text>
            ) : (
              draft.factors.map((f, i) => (
                <Tag key={`${f.name}-${i}`} color={f.kind === 'sentiment' ? 'purple' : 'cyan'}>
                  {f.name}
                </Tag>
              ))
            )}
          </Space>
        </div>

        {/* Transaction Cost */}
        <div className="agent-plan-field">
          <div className="agent-plan-field-header">
            <Text type="secondary" className="agent-plan-field-label">
              {t('plan.transactionCost')}
            </Text>
            <Button type="link" size="small" onClick={() => toggleEdit('cost')}>
              {isEditing('cost') ? t('plan.done') : t('plan.edit')}
            </Button>
          </div>
          {isEditing('cost') ? (
            <InputNumber
              value={draft.transaction_cost_bps}
              min={0}
              onChange={(v) =>
                setDraft({ ...draft, transaction_cost_bps: v ?? 0 })
              }
            />
          ) : (
            <Text>{draft.transaction_cost_bps} bps</Text>
          )}
        </div>

        {/* Validation */}
        <div className="agent-plan-field">
          <Text type="secondary" className="agent-plan-field-label">
            {t('plan.validation')}
          </Text>
          <div className="agent-plan-subfields">
            <div>
              <Text type="secondary" className="agent-plan-sublabel">
                {t('plan.baselines')}:
              </Text>{' '}
              <Space wrap>
                {draft.validation.baselines.map((b) => (
                  <Tag key={b}>{b}</Tag>
                ))}
              </Space>
            </div>
            <div>
              <Text type="secondary" className="agent-plan-sublabel">
                {t('plan.metrics')}:
              </Text>{' '}
              <Space wrap>
                {draft.validation.metrics.map((m) => (
                  <Tag key={m}>{m}</Tag>
                ))}
              </Space>
            </div>
            <div>
              <Text type="secondary" className="agent-plan-sublabel">
                {t('plan.costSensitivity')}:
              </Text>{' '}
              <Text>{draft.validation.cost_sensitivity_bps.join(', ')}</Text>
            </div>
          </div>
        </div>

        {/* Assumptions */}
        <div className="agent-plan-field">
          <Text type="secondary" className="agent-plan-field-label">
            {t('plan.assumptions')}
          </Text>
          <ul className="agent-plan-list">
            {draft.assumptions.map((a, i) => (
              <li key={i}>{a}</li>
            ))}
          </ul>
        </div>

        {/* Plan hash */}
        {planHash && (
          <div className="agent-plan-field">
            <Text type="secondary" className="agent-plan-field-label">
              {t('plan.hash')}
            </Text>
            <Text code className="agent-plan-hash">
              {planHash.substring(0, 16)}…
            </Text>
          </div>
        )}
      </div>

      {/* Approval gate */}
      <div className="agent-plan-approve">
        {!validationResult.success && (
          <Alert
            type="error"
            showIcon
            message={t('plan.invalid')}
            description={
              <ul className="agent-validation-list">
                {validationResult.error.issues.slice(0, 5).map((iss, i) => (
                  <li key={i}>
                    {iss.path.join('.')}: {iss.message}
                  </li>
                ))}
              </ul>
            }
            className="agent-alert"
          />
        )}
        <Button
          type="primary"
          size="large"
          icon={canApprove ? <PlayCircleOutlined /> : <CheckCircleOutlined />}
          loading={approving}
          disabled={!canApprove || !planHash}
          onClick={handleApprove}
        >
          {approving ? t('plan.approved') : t('plan.approveAndRun')}
        </Button>
      </div>
    </Card>
  );
}

export { PlanReview };
export type { PlanReviewProps };
export { PlanReview as default };
